website/views.py
# routes for website will be stored here, basically pages user can go to (home,study page, etc...)
# this file will contain URLs for our website
from flask import Blueprint, render_template, request, redirect, url_for, flash
# required to deal with user being logged in already and logging out
from flask_login import login_required, current_user
# to be able to create new deck
from .models import Deck, Flashcard
# to access the database (db) we created in __init__.py
from . import db
#
from website import extract_problem_names
from flask import jsonify

# set up blueprint for flask application
views = Blueprint('views', __name__)

# @nameOfBlueprint.route('URL to get to this endpoint')
@views.route('/home', methods = ['GET', 'POST'])
@login_required
# when user gets to this route, the following function will be ran
def home():
    if request.method == "POST":
        deck_name = request.form.get('deckName')
        try:
            for deck in current_user.decks:
                print(deck.name)
        except:
            print("unable to print user deck")
        deck_exists = Deck.query.filter_by(user_id = current_user.id, name = deck_name).first()
        if deck_exists:
            flash("Deck name already exists. Try a different name.", category='error')
        else:
            new_deck = Deck(name = deck_name, user_id = current_user.id)
            db.session.add(new_deck)
            db.session.commit()
            flash("New Deck Successfully created!", category='success')
            return redirect(url_for('views.home'))
    # passing curr_user allows us to reference user in template to check if authenticated
    return render_template("home.html", user = current_user)


@views.route('/study-session/<deck>')
def study_session(deck):
    deckID = Deck.query.filter_by(id = deck).first()
    return render_template("study_session.html", user = current_user, deck = deckID)


easy = extract_problem_names("LeetCodeEasy.txt")
medium = extract_problem_names("LeetCodeMedium.txt")
hard = extract_problem_names("LeetCodeHard.txt")
@views.route('/practice-problems')

def practice_problems():
    return render_template("practice_problems.html", user = current_user, easyProblems = easy, midProblems = medium, hardProblems = hard)


@views.route('/')
def initial():
    return render_template("initial.html", user = current_user)

# to delete a deck from any user
@views.route('/delete/<int:id>')
def delete(id):
    deck_to_delete = Deck.query.get_or_404(id)
    try:
        db.session.delete(deck_to_delete)
        db.session.commit()
        flash("Deck successfully deleted.", category='success')
        return redirect(url_for('views.home'))
    except:
        flash("Unable to delete deck.", category='error')
        return redirect(url_for('views.home'))
    
    
@views.route('/add/<int:id>/')
def add(id):
    try:
        problemName = request.args.get('flashName')
        new_flashcard = Flashcard(name = problemName, deck_id = id, user_id = current_user.id)
        db.session.add(new_flashcard)
        db.session.commit()
        flash("Problem Successfully Added", category='success')
        return redirect(url_for('views.practice_problems'))
    except:
        flash("Unable to add", category='error')
        return redirect(url_for('views.practice_problems'))

@views.route('/get_problems/<difficulty>')
def get_problems(difficulty):
    if difficulty == 'easy':
        problems = easy
    elif difficulty == 'medium':
        problems = medium
    elif difficulty == 'hard':
        problems = hard
    else:
        problems = easy + medium + hard
    
    return jsonify(problems)

website/templates/base.html
<!--This is base template, all other html will inherit template but overwrite as needed-->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS framework called boostrap, allows us to make website look good-->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="/node_modules/bootstrap/dist/css/bootstrap.min.css">

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <!-- to change background color, we import local css file basics.css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='basics.css') }}">

    <title>{% block title %}Base{% endblock %}</title>
  </head>
  <body>
    <!--This is the navigation bar, design taken from bootstrap-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <!--Defines the button in case we are in mobile device-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!--Define navigation items in navigation bar-->
        <div class="collapse navbar-collapse" id="navbar">
            <!--The actual navigation items-->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
              <a class="nav-item nav-link" id="home" href="/home">Home</a>
              <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
              {% else %}
              <a class="nav-item nav-link" id="login" href="/login">Login</a>
              <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
              {% endif %}
              <!--will show regardless if user logged in or not-->
              <a class="nav-item nav-link" id="practiceProblems" href="/practice-problems">Practice Problems</a>
            </div>
        </div>
    </nav>

    <!--messages is variable which will get all messages we flashed-->
    {% with messages = get_flashed_messages(with_categories = true) %}
      <!--check if we actually have messagest first-->
      {% if messages %}
        <!--if we have messages, we loop through all since we may have more than 1-->
        {% for category, message in messages %}
          <!-- if the flash message is an error category-->
          {% if category == 'error' %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
              <!--to actually show the message-->
              {{ message }}
              <button type="button" class="close" data-dismiss="alert">
                <!--to show the 'x' that closes the tab-->
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          <!-- if it's a success message-->
          {% else %}
            <div class="alert alert-success alter-dismissable fade show" role="alert">
              <!--to actually show the message-->
              {{ message }}
              <!--allow user to close message-->
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endwith %}

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    <!-- CSS framework called boostrap, allows us to make website look good-->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

website/templates/home.html
<!--To extend the base template from base.html-->
{% extends "base.html" %}

{% block title %}Home{% endblock %}
{% block content %}
<br />
<div class="container">
    <a href="#">
        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#exampleModalCenter">Add New Deck</button>
    </a>
    <a href="/practice-problems">
        <button type="button" class="btn btn-warning">Browse Problems</button>
    </a>
</div>
<br />

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <form method="POST">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Deck Name</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="deckName">Enter name for your new deck. You can add flashcards later.</label>
                        <!--the 'name' will allow us to access the email adress in the backend-->
                        <input type="text" class="form-control" id="deckName" name="deckName" placeholder="My Deck 1"/>
                    </div>
                    <br />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Exit</button>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>


<h1 align="center" >My Decks</h1>
<br />

{% for deck in user.decks %}
    <div class="rectangle">
        <a href="/study-session/{{ deck.id }}">
            <h3 class="center" style="color: white">{{ deck.name }}</h3>
        </a>
    </div>
    <a href="{{ url_for('views.delete', id = deck.id) }}">
        <h4 class="delete-button" style="color: rgb(234, 0, 0)">Delete</h4>
    </a>
    <br />
    <br />
{% endfor %}


<script>
    function openForm() {
      document.getElementById("myForm").style.display = "block";
    }
    
    function closeForm() {
      document.getElementById("myForm").style.display = "none";
    }
    </script>

{% endblock %}

website/templates/initial.html
<!--To extend the base template from base.html-->
{% extends "base.html" %}

{% block title %}Study Session Tab{% endblock %}

{% block content %}

<div class="container">
    <br />
    <div class="row text-center">
        <div class="col-md-6">
            <br />
            <h1 class="display-3"><strong>C-A-S-O</strong></h1>
            <!-- <br /> -->
            <!-- <br /> -->
            <h2 class="h2_initial">"Learning never exhausts the mind." - Leonardo da Vinci</h2>
            <!-- <br /> -->
            <p class="p_initial">Welcome to CASO, this website is designed to help users tackle their most difficult LeetCode questions/problems</p>
            <br />
        </div>
        <div class="col-md-6">
            <img src="/static/Flashcards.png" style="width: 100%;">
        </div>
    </div>
</div>

{% endblock %}

website/templates/login.html
<!--To extend the base template from base.html-->
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<form method="POST">
    <h2 align="center">Log in</h2>
    <!--form-group: a boostrap class to create labels to take info from user-->
    <div class="form-group">
        <label for="email">Email Address</label>
        <!--the 'name' will allow us to access the email adress in the backend-->
        <input type="email" class="form-control" id="email" name="email" placeholder="Email"/>
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Password"/>
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Log in</button>
</form>
{% endblock %}

website/templates/practice_problems.html
<!DOCTYPE html>
<html lang="en">
{% extends "base.html" %}

{% block title %}Practice Problems{% endblock %}

{% block content %}

<head>
    <!-- Add Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Add Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css">
    <!-- to change background color, we import local css file basics.css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='basics.css') }}">
    <style>
        .reset-btn {
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100%;
            white-space: nowrap;
        }

        .reset-btn > div {
            display: flex;
            flex-direction: column;
            align-items: center;
        }
    </style>
</head>

<body>
    <br />
    <h1 align="center"><strong>Practice Problems</strong></h1>
    <br />

    <!-- Difficulty Selection Dropdown -->
    <div class="d-flex justify-content-center mb-4">
        <select id="difficultySelect" class="form-select w-25">
            <option value="all">All Difficulties</option>
            <option value="easy">Easy</option>
            <option value="medium">Medium</option>
            <option value="hard">Hard</option>
        </select>
    </div>

    {% if user.is_authenticated %}

    <div id="problemsContainer">
        <!-- Problems will be dynamically inserted here -->
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const difficultySelect = document.getElementById('difficultySelect');
            const problemsContainer = document.getElementById('problemsContainer');
    
            function renderProblems(problems, difficulty) {
                problemsContainer.innerHTML = '';
    
                problems.forEach(problem => {
                    const problemName = problem.replace('-', ' ');
                    const problemElement = document.createElement('div');
                    problemElement.classList.add('d-flex', 'flex-column', 'align-items-center');
    
                    // Determine color based on difficulty
                    let colorClass = '';
                    if (difficulty === 'easy') {
                        colorClass = 'bg-success';
                    } else if (difficulty === 'medium') {
                        colorClass = 'bg-warning';
                    } else if (difficulty === 'hard') {
                        colorClass = 'bg-danger';
                    } else {
                        colorClass = 'bg-primary';
                    }
    
                    problemElement.innerHTML = `
                        <div class="btn-group btn-group-toggle mb-3 ${colorClass}">
                            <a href="https://leetcode.com/problems/${problem}/" target="_blank" class="btn reset-btn">
                                <div>
                                    <p class="mb-0">${problemName}</p>
                                    <p class="mb-0">Difficulty: ${difficulty.charAt(0).toUpperCase() + difficulty.slice(1)}</p>
                                </div>
                            </a>
                            <a href="#">
                                <button type="button" class="btn reset-btn btn-lg" data-toggle="modal" data-target="#exampleModalCenter${problem}">
                                    <i class="fa-solid fa-plus"></i>
                                </button>
                            </a>
                            <div class="modal fade" id="exampleModalCenter${problem}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document" id="${problem}">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLongTitle">Deck Name</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <div class="form-group">
                                                <label for="deckName">Which deck would you like to add the problem in?</label>
                                                <div class="dropdown">
                                                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                                                        Your Decks 👩‍💻
                                                        <span class="caret"></span>
                                                    </button>
                                                    <ul class="dropdown-menu">
                                                        {% for deck in user.decks %}
                                                            <li><a href="{{ url_for('views.add', id=deck.id) }}?flashName=${problem.replace('-', ' ')}">{{ deck.name }}</a></li>
                                                        {% endfor %}
                                                    </ul>
                                                </div>
                                            </div>
                                            <br />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    `;
                    problemsContainer.appendChild(problemElement);
                });
            }
    
            async function fetchProblems(difficulty) {
                const response = await fetch(`/get_problems/${difficulty}`);
                const problems = await response.json();
                renderProblems(problems, difficulty);
            }
    
            difficultySelect.addEventListener('change', (e) => {
                const selectedDifficulty = e.target.value;
                fetchProblems(selectedDifficulty);
            });
    
            // Initial rendering of all problems
            fetchProblems('all');
        });
    </script>
    
    {% else %}
    <br />
    <h1 class="center">Please <a href="/login">Log-in</a> or <a href="/sign-up">Sign-up</a> to access our list of problems!</h1>

    {% endif %}

{% endblock %}
</body>
</html>

website/templates/sign_up.html
<!--To extend the base template from base.html-->
{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<!--method post means we will send the data to web server to be processed-->
<form method="POST">
    <!--We now have a sign up string in center of website-->
    <h3 align="center">Sign Up</h3>
    <!--form-group: a boostrap class to create labels to take info from user-->
    <div class="form-group">
        <label for="email">Email Address</label>
        <!--the 'name' parameter will allow us to access the email adress in the backend-->
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter Email"/>
    </div>
    <div class="form-group">
        <label for="firstName">First Name</label>
        <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Enter First Name"/>
    </div>
    <div class="form-group">
        <label for="lastName">Last Name</label>
        <input type="text" class="form-control" id="lastName" name="lastName" placeholder="Enter Last Name"/>
    </div>
    <div class="form-group">
        <label for="password1">Password</label>
        <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter Password"/>
    </div>
    <div class="form-group">
        <label for="password2">Re-enter Password</label>
        <input type="password" class="form-control" id="password2" name="password2" placeholder="Re-enter Password"/>
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

website/templates/study_session.html
<!--To extend the base template from base.html-->
{% extends "base.html" %}

{% block title %}Study Session Tab{% endblock %}

{% block content %}

<br/>
<h1 class="center" class="display-3">{{ deck.name }}</h1>

{% for flashcard in deck.flashcards %}
    <div class="flip-card">
        <div class="flip-card-inner">
        <div class="flip-card-front">
            <h3 class="center">{{ flashcard.name }}</h3>
        </div>
        <div class="flip-card-back">
            <p class="center"><a href="https://leetcode.com/problems/{{ flashcard.name.replace(' ', '-') }}/" target="_blank">Try LeetCode Solution</a></p>
        </div>
        </div>
    </div>
<br />
{% endfor %}

{% endblock %}